name: Deploy with Docker Compose && Traefik

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    # noinspection YAMLSchemaValidation
    runs-on: linux

    steps:
    - uses: actions/checkout@v3
    - name: Run server
      run: docker compose -f docker-compose-traefik.yml up --build -d
